import {
  getFetcher,
  postFetcher,
  putFetcher,
  patchFetcher,
  deleteFetcher,
} from "./apiHelper";
import * as url from "./urlHelper";

/**
 * @author Faruk Uçgun
 * @date 18.12.2024
 * @abstract: This file is responsible for making requests to backend
 */

// auth
export const login = async (data) => {
  return await postFetcher(url.LOGIN_PATH(), data);
};

export const loginGoogle = async (data) => {
  return await postFetcher(url.LOGIN_GOOGLE_PATH(), data);
};

export const register = async (data) => {
  return await postFetcher(url.REGISTER_PATH(), data);
};

// deck
export const createDeck = async (data) => {
  return await postFetcher(url.CREATE_DECK_PATH(), data);
};

export const deleteDeck = async (id) => {
  return await deleteFetcher(url.DELETE_DECK_PATH(id));
};

export const getDecksByCurrentUser = async () => {
  return await getFetcher(url.GET_DECKS_BY_CURRENT_USER());
};

export const getDeckByDeckId = async (id) => {
  return await getFetcher(url.GET_DECK_BY_DECK_ID_PATH(id));
};

export const getDecksByUserId = async (id) => {
  return await getFetcher(url.GET_DECKS_BY_USER_ID_PATH(id));
};

export const generateDeckShareToken = async (id) => {
  return await postFetcher(url.GENERATE_DECK_SHARE_TOKEN_PATH(id));
};

export const getDeckByShareToken = async (shareToken) => {
  return await getFetcher(url.GET_DECK_BY_SHARE_TOKEN_PATH(shareToken));
};

export const addUserDeck = async (id) => {
  return await postFetcher(url.ADD_USER_DECK_PATH(id));
};

export const updateDeckName = async (id, data) => {
  return await putFetcher(url.UPDATE_DECK_NAME_PATH(id), data);
};

export const changeDeckVisibility = async (id) => {
  return await patchFetcher(url.CHANGE_DECK_VISIBILITY_PATH(id));
};

export const discoverDecks = async (sortionOption) => {
  return await getFetcher(url.DISCOVER_DECKS_PATH(sortionOption));
};

export const likeDeck = async (id) => {
  return await patchFetcher(url.LIKE_DECK_PATH(id));
};

export const dislikeDeck = async (id) => {
  return await patchFetcher(url.DISLIKE_DECK_PATH(id));
};

// deck statistics
export const createDeckStats = async (data) => {
  return await postFetcher(url.CREATE_DECK_STATS_PATH(), data);
};

// flashcard
export const createFlashcard = async (data) => {
  return await postFetcher(url.CREATE_FLASHCARD_PATH(), data, "multipart/form-data");
};

export const updateFlashcard = async (id, data) => {
  return await putFetcher(url.UPDATE_FLASHCARD_PATH(id), data, "multipart/form-data");
};

export const deleteFlashcard = async (id, data) => {
  return await deleteFetcher(url.DELETE_FLASHCARD_PATH(id), data);
};

export const getFlashcardsInBatch = async (deckId) => {
  return await getFetcher(url.GET_FLASHCARDS_IN_BATCH_PATH(deckId));
};

export const updateFlashcardReviews = async (data) => {
  return await postFetcher(url.UPDATE_FLASHCARD_REVIEWS_PATH(), data);
};

export const generateDeck = async (data) => {
  return await postFetcher(
    url.GENERATE_DECK_PATH(),
    data,
    "multipart/form-data"
  );
};

export const sendForgotPasswordCode = async (data) => {
  return await postFetcher(url.FORGOT_PASSWORD_PATH(), data);
};

export const verifyResetPasswordcode = async (data) => {
  return await postFetcher(url.VERIFY_RESET_PASSWORD_CODE_PATH(), data);
};

export const resetPassword = async (data) => {
  return await postFetcher(url.RESET_PASSWORD_PATH(), data);
};

export const createFeedback = async (data) => {
  return await postFetcher(url.CREATE_FEEDBACK_PATH(), data);
};

export const autoGenerateDeck = async (formData) => {
  return await postFetcher(
    url.AUTO_GENERATE_DECK_PATH(),
    formData,
    "multipart/form-data"
  );
};

// quiz
export const getQuizzesByCurrentUser = async () => {
  return await getFetcher(url.GET_QUIZZES_BY_CURRENT_USER_PATH());
};

export const deleteQuiz = async (id) => {
  return await deleteFetcher(url.DELETE_QUIZ_PATH(id));
};

export const createQuiz = async (data) => {
  return await postFetcher(url.CREATE_QUIZ_PATH(), data);
};

export const getQuizByQuizId = async (id) => {
  return await getFetcher(url.GET_QUIZ_BY_QUIZ_ID_PATH(id));
};

export const autoGenerateQuiz = async (formData) => {
  return await postFetcher(
    url.AUTO_GENERATE_QUIZ_PATH(),
    formData,
    "multipart/form-data"
  );
};

export const changeQuizVisibility = async (id) => {
  return await patchFetcher(url.CHANGE_QUIZ_VISIBILITY_PATH(id));
};

export const discoverQuizzes = async (sortionOption) => {
  return await getFetcher(url.DISCOVER_QUIZZES_PATH(sortionOption));
};

export const likeQuiz = async (id) => {
  return await patchFetcher(url.LIKE_QUIZ_PATH(id));
};

export const dislikeQuiz = async (id) => {
  return await patchFetcher(url.DISLIKE_QUIZ_PATH(id));
};

export const getUserProfile = async () => {
  return await getFetcher(url.GET_USER_PROFILE());
};

export const generalSearch = async (searchText) => {
  return await getFetcher(url.SEARCH_PATH(searchText));
};

export const decksSearch = async (searchText) => {
  return await getFetcher(url.SEARCH_DECKS_PATH(searchText));
};

export const quizzesSearch = async (searchText) => {
  return await getFetcher(url.SEARCH_QUIZZES_PATH(searchText));
};

export const decksOthersSearch = async (searchText) => {
  return await getFetcher(url.SEARCH_OTHERS_DECKS_PATH(searchText));
};

export const quizzesOthersSearch = async (searchText) => {
  return await getFetcher(url.SEARCH_OTHERS_QUIZZES_PATH(searchText));
};

export const generateQuizShareToken = async (id) => {
  return await postFetcher(url.GENERATE_QUIZ_SHARE_TOKEN_PATH(id));
};

export const getQuizByShareToken = async (shareToken) => {
  return await getFetcher(url.GET_QUIZ_BY_SHARE_TOKEN_PATH(shareToken));
};

export const addUserQuiz = async (id) => {
  return await postFetcher(url.ADD_USER_QUIZ_PATH(id));
};

export const updateQuizName = async (id, data) => {
  return await putFetcher(url.UPDATE_QUIZ_NAME_PATH(id), data);
};

// quiz statistics
export const createQuizStats = async (data) => {
  return await postFetcher(url.CREATE_QUIZ_STATS_PATH(), data);
};

// question
export const removeQuestion = async (id, data) => {
  return await deleteFetcher(url.REMOVE_QUESTION_PATH(id), data);
};

export const createQuestion = async (data) => {
  return await postFetcher(url.CREATE_QUESTION_PATH(), data);
};

export const editQuestion = async (id, data) => {
  return await putFetcher(url.EDIT_QUESTION_PATH(id), data);
};
